// Generated by CoffeeScript 1.9.3
$(function() {
  setTimeout("$('#title-text').transition({ animation: 'fly left' });", 500);
  setTimeout("$('#wrapper .ui.card').transition({ animation: 'fade up', duration: 600, });", 1000);
  return setTimeout("$('#knit').transition({ animation: 'bounce' });", 1600);
});
