// Generated by CoffeeScript 1.9.3
$(function() {
  var $inputDir, $inputLeft, $inputTop;
  $inputTop = $('input[name=top]');
  $inputLeft = $('input[name=left]');
  $inputDir = $('input[name=dir]');
  $('#knit').draggable({
    containment: '#workspace',
    stop: function(event, ui) {
      $inputTop.val(ui.position.top);
      return $inputLeft.val(ui.position.left);
    }
  });
  return $('#knit').dblclick(function() {
    var currentDir;
    $(this).toggleClass("reversed");
    currentDir = $inputDir.val();
    return $inputDir.val((currentDir - 0) * -1);
  });
});
